tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "schniz/tap"

brew "axel"
brew "curl"
brew "fzf"
brew "git"
brew "gnupg"
brew "htop"
brew "mas"
brew "neovim"
brew "openssl"
brew "python"
brew "qemu"
brew "rustup"
brew "tmux"
brew "tmuxinator"
brew "starship"
brew "yarn"
brew "zsh"

cask "basecamp"
cask "emacs"
cask "firefox"
cask "font-hack-nerd-font"
cask "iterm2"
cask "slack"
cask "spotify"
cask "telegram"
cask "visual-studio-code"
cask "dbeaver-community"
cask "transmission"
cask "fork"

mas "1Password", id: 443987910
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
